version: '3.4'
services:
  wordpress:
    image: wordpress:5.4-php7.4-fpm-alpine
    depends_on:
      - database
    links:
      - database:mysql
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}

  webserver:
    image: nginx:1.14-alpine
    restart: always
    links:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./docker/nginx/website.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${WEBSERVER_PORT}:80

volumes:
  db_data: {}
  wordpress_data: {}
